// Offline-Katalog bekannter Cocktails für die Vorschlagsliste im
// "Hinzufügen"-Dialog. Er ersetzt die frühere Live-Suche bei TheCocktailDB:
// keine Netzwerkanfrage, kein API-Schlüssel, keine Kosten - und die Suche
// antwortet sofort, auch im Flugmodus.
//
// Die Reihenfolge ist grob nach Bekanntheit sortiert; die ersten Einträge
// erscheinen als Vorschläge, solange noch nichts getippt wurde.
// Die Zutaten stehen im selben Format wie in shared/data.js (Menge + Zutat
// in einem Text), damit die Art-Erkennung und die Alkoholmenge sie lesen.
const cocktailCatalog = [
  { name: "Mojito", ingredients: ["2 oz Light Rum", "1 oz Lime Juice", "2 tsp Sugar", "8 Mint Leaves", "3 oz Soda Water"] },
  { name: "Margarita", ingredients: ["2 oz Tequila", "1 oz Triple Sec", "1 oz Lime Juice"] },
  { name: "Aperol Spritz", ingredients: ["2 oz Aperol", "3 oz Prosecco", "1 oz Soda Water"] },
  { name: "Moscow Mule", ingredients: ["2 oz Vodka", "1/2 oz Lime Juice", "4 oz Ginger Beer"] },
  { name: "Daiquiri", ingredients: ["2 oz Light Rum", "1 oz Lime Juice", "3/4 oz Simple Syrup"] },
  { name: "Old Fashioned", ingredients: ["2 oz Bourbon", "1 tsp Sugar", "3 Dashes Angostura Bitters"] },
  { name: "Whiskey Sour", ingredients: ["2 oz Bourbon", "1 oz Lemon Juice", "3/4 oz Simple Syrup", "1/2 oz Egg White"] },
  { name: "Caipirinha", ingredients: ["2 oz Cachaca", "1 Lime", "2 tsp Sugar"] },
  { name: "Cosmopolitan", ingredients: ["1 1/2 oz Vodka Citron", "1/2 oz Triple Sec", "1/2 oz Lime Juice", "1 oz Cranberry Juice"] },
  { name: "Espresso Martini", ingredients: ["2 oz Vodka", "1/2 oz Kahlua", "1 oz Espresso", "1/4 oz Simple Syrup"] },
  { name: "Hugo", ingredients: ["1 oz Elderflower Syrup", "4 oz Prosecco", "1 oz Soda Water", "8 Mint Leaves", "2 Lime Wedges"] },
  { name: "Long Island Iced Tea", ingredients: ["1/2 oz Vodka", "1/2 oz Light Rum", "1/2 oz Gin", "1/2 oz Tequila", "1/2 oz Triple Sec", "3/4 oz Lemon Juice", "2 oz Cola"] },
  { name: "Sex on the Beach", ingredients: ["1 1/2 oz Vodka", "1/2 oz Peach Schnapps", "2 oz Orange Juice", "2 oz Cranberry Juice"] },
  { name: "Mai Tai", ingredients: ["1 1/2 oz Dark Rum", "1/2 oz Light Rum", "1/2 oz Orange Curacao", "1/2 oz Orgeat Syrup", "1 oz Lime Juice"] },
  { name: "Manhattan", ingredients: ["2 oz Rye Whiskey", "1 oz Sweet Vermouth", "2 Dashes Angostura Bitters"] },
  { name: "Gin Fizz", ingredients: ["2 oz Gin", "1 oz Lemon Juice", "3/4 oz Simple Syrup", "3 oz Soda Water"] },
  { name: "Tom Collins", ingredients: ["2 oz Gin", "1 oz Lemon Juice", "1/2 oz Simple Syrup", "3 oz Soda Water"] },
  { name: "Bloody Mary", ingredients: ["2 oz Vodka", "4 oz Tomato Juice", "1/2 oz Lemon Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco", "1 Pinch Celery Salt"] },
  { name: "Screwdriver", ingredients: ["2 oz Vodka", "4 oz Orange Juice"] },
  { name: "Gin Basil Smash", ingredients: ["2 oz Gin", "1 oz Lemon Juice", "3/4 oz Simple Syrup", "10 Basil Leaves"] },
  { name: "Paloma", ingredients: ["2 oz Tequila", "1/2 oz Lime Juice", "4 oz Grapefruit Soda", "1 Pinch Salt"] },
  { name: "Dark and Stormy", ingredients: ["2 oz Dark Rum", "4 oz Ginger Beer", "1/2 oz Lime Juice"] },
  { name: "Pisco Sour", ingredients: ["2 oz Pisco", "1 oz Lime Juice", "3/4 oz Simple Syrup", "1/2 oz Egg White", "2 Dashes Angostura Bitters"] },
  { name: "Amaretto Sour", ingredients: ["2 oz Amaretto", "1 oz Lemon Juice", "1/2 oz Simple Syrup", "1/2 oz Egg White"] },
  { name: "White Russian", ingredients: ["2 oz Vodka", "1 oz Kahlua", "1 oz Cream"] },
  { name: "Mint Julep", ingredients: ["2 1/2 oz Bourbon", "1/2 oz Simple Syrup", "10 Mint Leaves"] },
  { name: "Sidecar", ingredients: ["2 oz Cognac", "3/4 oz Triple Sec", "3/4 oz Lemon Juice"] },
  { name: "Aviation", ingredients: ["2 oz Gin", "1/2 oz Maraschino Liqueur", "1/4 oz Creme de Violette", "3/4 oz Lemon Juice"] },
  { name: "Sazerac", ingredients: ["2 oz Rye Whiskey", "1 Sugar Cube", "3 Dashes Peychaud Bitters", "1 Dash Absinthe"] },
  { name: "Boulevardier", ingredients: ["1 1/2 oz Bourbon", "1 oz Campari", "1 oz Sweet Vermouth"] },
  { name: "Americano", ingredients: ["1 1/2 oz Campari", "1 1/2 oz Sweet Vermouth", "2 oz Soda Water"] },
  { name: "Bramble", ingredients: ["2 oz Gin", "1 oz Lemon Juice", "1/2 oz Simple Syrup", "1/2 oz Creme de Mure"] },
  { name: "French 75", ingredients: ["1 oz Gin", "1/2 oz Lemon Juice", "1/2 oz Simple Syrup", "3 oz Champagne"] },
  { name: "Zombie", ingredients: ["1 1/2 oz Dark Rum", "1 1/2 oz Light Rum", "1 oz Overproof Rum", "1/2 oz Falernum", "1 oz Lime Juice", "1 oz Grapefruit Juice", "1 tsp Grenadine"] },
  { name: "Hurricane", ingredients: ["2 oz Dark Rum", "2 oz Light Rum", "1 oz Passion Fruit Syrup", "1 oz Lime Juice", "1 oz Orange Juice"] },
  { name: "Painkiller", ingredients: ["2 oz Dark Rum", "4 oz Pineapple Juice", "1 oz Orange Juice", "1 oz Coconut Cream", "1 Pinch Nutmeg"] },
  { name: "Blue Hawaii", ingredients: ["1 oz Light Rum", "1 oz Vodka", "1 oz Blue Curacao", "3 oz Pineapple Juice", "1 oz Sweet and Sour Mix"] },
  { name: "Swimming Pool", ingredients: ["1 1/2 oz Vodka", "1/2 oz Light Rum", "1 oz Coconut Cream", "3 oz Pineapple Juice", "1/2 oz Blue Curacao"] },
  { name: "Sea Breeze", ingredients: ["1 1/2 oz Vodka", "3 oz Cranberry Juice", "1 1/2 oz Grapefruit Juice"] },
  { name: "Bay Breeze", ingredients: ["1 1/2 oz Vodka", "3 oz Cranberry Juice", "1 1/2 oz Pineapple Juice"] },
  { name: "Madras", ingredients: ["1 1/2 oz Vodka", "3 oz Cranberry Juice", "1 1/2 oz Orange Juice"] },
  { name: "Woo Woo", ingredients: ["1 1/2 oz Vodka", "1 oz Peach Schnapps", "3 oz Cranberry Juice"] },
  { name: "Kamikaze", ingredients: ["1 oz Vodka", "1 oz Triple Sec", "1 oz Lime Juice"] },
  { name: "Lemon Drop Martini", ingredients: ["2 oz Vodka Citron", "1/2 oz Triple Sec", "3/4 oz Lemon Juice", "1/2 oz Simple Syrup"] },
  { name: "Appletini", ingredients: ["2 oz Vodka", "1 oz Apple Liqueur", "1/2 oz Lemon Juice"] },
  { name: "Pornstar Martini", ingredients: ["2 oz Vanilla Vodka", "1/2 oz Passoa", "1 oz Passion Fruit Puree", "1/2 oz Lime Juice", "2 oz Prosecco"] },
  { name: "French Martini", ingredients: ["2 oz Vodka", "1/2 oz Chambord", "2 oz Pineapple Juice"] },
  { name: "Clover Club", ingredients: ["2 oz Gin", "1/2 oz Raspberry Syrup", "3/4 oz Lemon Juice", "1/2 oz Egg White"] },
  { name: "Last Word", ingredients: ["3/4 oz Gin", "3/4 oz Green Chartreuse", "3/4 oz Maraschino Liqueur", "3/4 oz Lime Juice"] },
  { name: "Corpse Reviver No. 2", ingredients: ["3/4 oz Gin", "3/4 oz Cointreau", "3/4 oz Lillet Blanc", "3/4 oz Lemon Juice", "1 Dash Absinthe"] },
  { name: "Vesper", ingredients: ["3 oz Gin", "1 oz Vodka", "1/2 oz Lillet Blanc"] },
  { name: "Gimlet", ingredients: ["2 oz Gin", "3/4 oz Lime Juice", "1/2 oz Simple Syrup"] },
  { name: "Southside", ingredients: ["2 oz Gin", "1 oz Lime Juice", "3/4 oz Simple Syrup", "8 Mint Leaves"] },
  { name: "Bees Knees", ingredients: ["2 oz Gin", "3/4 oz Lemon Juice", "3/4 oz Honey Syrup"] },
  { name: "Penicillin", ingredients: ["2 oz Blended Scotch", "3/4 oz Lemon Juice", "3/4 oz Honey Ginger Syrup", "1/4 oz Islay Scotch"] },
  { name: "Godfather", ingredients: ["2 oz Scotch", "1 oz Amaretto"] },
  { name: "Godmother", ingredients: ["2 oz Vodka", "1 oz Amaretto"] },
  { name: "Rusty Nail", ingredients: ["2 oz Scotch", "1 oz Drambuie"] },
  { name: "Rob Roy", ingredients: ["2 oz Scotch", "1 oz Sweet Vermouth", "2 Dashes Angostura Bitters"] },
  { name: "Vieux Carre", ingredients: ["1 oz Rye Whiskey", "1 oz Cognac", "1 oz Sweet Vermouth", "1 tsp Benedictine", "2 Dashes Peychaud Bitters"] },
  { name: "Brooklyn", ingredients: ["2 oz Rye Whiskey", "1 oz Dry Vermouth", "1/4 oz Maraschino Liqueur", "1/4 oz Amaro"] },
  { name: "Martinez", ingredients: ["1 1/2 oz Gin", "1 1/2 oz Sweet Vermouth", "1 tsp Maraschino Liqueur", "2 Dashes Orange Bitters"] },
  { name: "Hanky Panky", ingredients: ["1 1/2 oz Gin", "1 1/2 oz Sweet Vermouth", "2 Dashes Fernet Branca"] },
  { name: "Negroni Sbagliato", ingredients: ["1 oz Campari", "1 oz Sweet Vermouth", "2 oz Prosecco"] },
  { name: "Garibaldi", ingredients: ["1 1/2 oz Campari", "4 oz Orange Juice"] },
  { name: "Bicicletta", ingredients: ["1 1/2 oz Campari", "3 oz White Wine", "1 oz Soda Water"] },
  { name: "Campari Spritz", ingredients: ["2 oz Campari", "3 oz Prosecco", "1 oz Soda Water"] },
  { name: "Limoncello Spritz", ingredients: ["2 oz Limoncello", "3 oz Prosecco", "1 oz Soda Water"] },
  { name: "Lillet Wild Berry", ingredients: ["2 oz Lillet Blanc", "4 oz Wild Berry Lemonade"] },
  { name: "Lillet Vive", ingredients: ["2 oz Lillet Blanc", "4 oz Tonic Water", "2 Strawberries", "6 Mint Leaves"] },
  { name: "Aperol Sour", ingredients: ["2 oz Aperol", "1 oz Lemon Juice", "1/2 oz Simple Syrup", "1/2 oz Egg White"] },
  { name: "Mimosa", ingredients: ["3 oz Champagne", "3 oz Orange Juice"] },
  { name: "Bucks Fizz", ingredients: ["4 oz Champagne", "2 oz Orange Juice"] },
  { name: "Champagne Cocktail", ingredients: ["4 oz Champagne", "1 Sugar Cube", "2 Dashes Angostura Bitters", "1/4 oz Cognac"] },
  { name: "Death in the Afternoon", ingredients: ["1 oz Absinthe", "4 oz Champagne"] },
  { name: "Kir", ingredients: ["4 oz White Wine", "1/2 oz Creme de Cassis"] },
  { name: "Rossini", ingredients: ["4 oz Prosecco", "2 oz Strawberry Puree"] },
  { name: "Sgroppino", ingredients: ["2 oz Prosecco", "1 oz Vodka", "2 Scoops Lemon Sorbet"] },
  { name: "Caipiroska", ingredients: ["2 oz Vodka", "1 Lime", "2 tsp Sugar"] },
  { name: "Caipirissima", ingredients: ["2 oz Light Rum", "1 Lime", "2 tsp Sugar"] },
  { name: "Batida de Coco", ingredients: ["2 oz Cachaca", "2 oz Coconut Milk", "1 oz Condensed Milk"] },
  { name: "Ti Punch", ingredients: ["2 oz Rhum Agricole", "1 tsp Cane Syrup", "1 Lime Wedge"] },
  { name: "Strawberry Daiquiri", ingredients: ["2 oz Light Rum", "1 oz Lime Juice", "1/2 oz Simple Syrup", "5 Strawberries"] },
  { name: "Frozen Margarita", ingredients: ["2 oz Tequila", "1 oz Triple Sec", "1 oz Lime Juice", "1 Cup Crushed Ice"] },
  { name: "Tommys Margarita", ingredients: ["2 oz Tequila", "1 oz Lime Juice", "1/2 oz Agave Syrup"] },
  { name: "Michelada", ingredients: ["0,33 l Lager Beer", "1 oz Lime Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco", "1 Pinch Salt"] },
  { name: "Bloody Caesar", ingredients: ["2 oz Vodka", "4 oz Clamato Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco"] },
  { name: "El Diablo", ingredients: ["2 oz Tequila", "1/2 oz Creme de Cassis", "1/2 oz Lime Juice", "3 oz Ginger Beer"] },
  { name: "Batanga", ingredients: ["2 oz Tequila", "1/2 oz Lime Juice", "4 oz Cola", "1 Pinch Salt"] },
  { name: "Mezcal Negroni", ingredients: ["1 oz Mezcal", "1 oz Campari", "1 oz Sweet Vermouth"] },
  { name: "Oaxaca Old Fashioned", ingredients: ["1 1/2 oz Tequila", "1/2 oz Mezcal", "1 tsp Agave Syrup", "2 Dashes Angostura Bitters"] },
  { name: "Naked and Famous", ingredients: ["3/4 oz Mezcal", "3/4 oz Yellow Chartreuse", "3/4 oz Aperol", "3/4 oz Lime Juice"] },
  { name: "Jungle Bird", ingredients: ["1 1/2 oz Dark Rum", "3/4 oz Campari", "1 1/2 oz Pineapple Juice", "1/2 oz Lime Juice", "1/2 oz Simple Syrup"] },
  { name: "Chi Chi", ingredients: ["2 oz Vodka", "1 oz Coconut Cream", "3 oz Pineapple Juice"] },
  { name: "Rum Runner", ingredients: ["1 oz Dark Rum", "1 oz Light Rum", "1/2 oz Banana Liqueur", "1/2 oz Blackberry Liqueur", "1 oz Lime Juice", "1/2 oz Grenadine"] },
  { name: "Bahama Mama", ingredients: ["1 oz Dark Rum", "1 oz Coconut Rum", "2 oz Pineapple Juice", "1 oz Orange Juice", "1/2 oz Grenadine"] },
  { name: "Miami Vice", ingredients: ["1 oz Light Rum", "1 oz Coconut Cream", "2 oz Pineapple Juice", "2 oz Strawberry Puree"] },
  { name: "Mudslide", ingredients: ["1 oz Vodka", "1 oz Kahlua", "1 oz Baileys", "1 oz Cream"] },
  { name: "Grasshopper", ingredients: ["1 oz Creme de Menthe", "1 oz Creme de Cacao", "1 oz Cream"] },
  { name: "Brandy Alexander", ingredients: ["1 1/2 oz Cognac", "1 oz Creme de Cacao", "1 oz Cream"] },
  { name: "Golden Cadillac", ingredients: ["1 oz Galliano", "1 oz Creme de Cacao", "1 oz Cream"] },
  { name: "Toasted Almond", ingredients: ["1 oz Amaretto", "1 oz Kahlua", "2 oz Cream"] },
  { name: "B-52", ingredients: ["1/2 oz Kahlua", "1/2 oz Baileys", "1/2 oz Grand Marnier"] },
  { name: "Baby Guinness", ingredients: ["3/4 oz Kahlua", "1/4 oz Baileys"] },
  { name: "Slippery Nipple", ingredients: ["3/4 oz Sambuca", "3/4 oz Baileys", "1 Dash Grenadine"] },
  { name: "Mexicaner", ingredients: ["4 cl Vodka", "2 cl Tomatensaft", "1 cl Chilisauce", "1 Spritzer Zitronensaft"] },
  { name: "Jägerbomb", ingredients: ["1 oz Jägermeister", "0,25 l Energydrink"] },
  { name: "Irish Coffee", ingredients: ["1 1/2 oz Irish Whiskey", "4 oz Coffee", "1 tsp Brown Sugar", "1 oz Whipped Cream"] },
  { name: "Espresso Tonic", ingredients: ["1 oz Espresso", "5 oz Tonic Water"] },
  { name: "Lumumba", ingredients: ["1 1/2 oz Brandy", "5 oz Hot Chocolate", "1 oz Whipped Cream"] },
  { name: "Snowball", ingredients: ["2 oz Advocaat", "1/2 oz Lime Juice", "4 oz Lemonade"] },
  { name: "Egg Nog", ingredients: ["1 1/2 oz Brandy", "1/2 oz Dark Rum", "1 Egg", "1 tsp Sugar", "4 oz Milk", "1 Pinch Nutmeg"] },
  { name: "Hot Toddy", ingredients: ["2 oz Whisky", "1 tsp Honey", "1/2 oz Lemon Juice", "4 oz Hot Water"] },
  { name: "Glühwein", ingredients: ["0,2 l Rotwein", "1 tsp Zucker", "1 Zimtstange", "2 Nelken", "1 Orangenscheibe"] },
  { name: "Feuerzangenbowle", ingredients: ["0,2 l Rotwein", "1 oz Overproof Rum", "1 Zuckerhut", "1 Zimtstange", "1 Orangenscheibe"] },
  { name: "Pimms Cup", ingredients: ["2 oz Pimms No. 1", "4 oz Lemonade", "1 Cucumber Slice", "6 Mint Leaves"] },
  { name: "Salty Dog", ingredients: ["2 oz Vodka", "4 oz Grapefruit Juice", "1 Pinch Salt"] },
  { name: "Greyhound", ingredients: ["2 oz Vodka", "4 oz Grapefruit Juice"] },
  { name: "Harvey Wallbanger", ingredients: ["1 1/2 oz Vodka", "4 oz Orange Juice", "1/2 oz Galliano"] },
  { name: "Fuzzy Navel", ingredients: ["2 oz Peach Schnapps", "4 oz Orange Juice"] },
  { name: "Melon Ball", ingredients: ["1 oz Vodka", "1 oz Midori", "3 oz Pineapple Juice"] },
  { name: "Midori Sour", ingredients: ["2 oz Midori", "1 oz Lemon Juice", "1/2 oz Simple Syrup", "2 oz Soda Water"] },
  { name: "Japanese Slipper", ingredients: ["1 oz Midori", "1 oz Cointreau", "1 oz Lemon Juice"] },
  { name: "Illusion", ingredients: ["1 oz Vodka", "1 oz Midori", "1/2 oz Triple Sec", "2 oz Pineapple Juice"] },
  { name: "Scorpion", ingredients: ["2 oz Light Rum", "1 oz Brandy", "2 oz Orange Juice", "1 oz Lemon Juice", "1/2 oz Orgeat Syrup"] },
  { name: "Fog Cutter", ingredients: ["1 1/2 oz Light Rum", "1/2 oz Gin", "1/2 oz Brandy", "1 oz Orange Juice", "1/2 oz Lemon Juice", "1/2 oz Orgeat Syrup"] },
  { name: "Three Dots and a Dash", ingredients: ["1 1/2 oz Rhum Agricole", "1/2 oz Dark Rum", "1/2 oz Honey Syrup", "1/2 oz Falernum", "1/2 oz Lime Juice", "1/2 oz Orange Juice"] },
  { name: "Singapore Sling", ingredients: ["1 1/2 oz Gin", "1/2 oz Cherry Brandy", "1/4 oz Cointreau", "1/4 oz Benedictine", "1/2 oz Lime Juice", "2 oz Pineapple Juice", "1/4 oz Grenadine"] },
  { name: "Hemingway Daiquiri", ingredients: ["2 oz Light Rum", "3/4 oz Lime Juice", "1/2 oz Grapefruit Juice", "1/4 oz Maraschino Liqueur"] },
  { name: "Between the Sheets", ingredients: ["1 oz Cognac", "1 oz Light Rum", "1 oz Triple Sec", "1/2 oz Lemon Juice"] },
  { name: "Mary Pickford", ingredients: ["2 oz Light Rum", "1 1/2 oz Pineapple Juice", "1 tsp Maraschino Liqueur", "1 tsp Grenadine"] },
  { name: "El Presidente", ingredients: ["2 oz Light Rum", "3/4 oz Dry Vermouth", "1/2 oz Orange Curacao", "1 tsp Grenadine"] },
  { name: "Bacardi Cocktail", ingredients: ["2 oz Bacardi Light Rum", "3/4 oz Lime Juice", "1/2 oz Grenadine"] },
  { name: "New York Sour", ingredients: ["2 oz Bourbon", "1 oz Lemon Juice", "3/4 oz Simple Syrup", "1/2 oz Red Wine"] },
  { name: "Paper Plane", ingredients: ["3/4 oz Bourbon", "3/4 oz Aperol", "3/4 oz Amaro Nonino", "3/4 oz Lemon Juice"] },
  { name: "Gold Rush", ingredients: ["2 oz Bourbon", "3/4 oz Lemon Juice", "3/4 oz Honey Syrup"] },
  { name: "Whiskey Smash", ingredients: ["2 oz Bourbon", "3/4 oz Lemon Juice", "1/2 oz Simple Syrup", "8 Mint Leaves"] },
  { name: "Blood and Sand", ingredients: ["3/4 oz Scotch", "3/4 oz Cherry Heering", "3/4 oz Sweet Vermouth", "3/4 oz Orange Juice"] },
  { name: "Suffering Bastard", ingredients: ["1 oz Gin", "1 oz Brandy", "1/2 oz Lime Juice", "4 oz Ginger Beer", "2 Dashes Angostura Bitters"] },
  { name: "Kentucky Mule", ingredients: ["2 oz Bourbon", "1/2 oz Lime Juice", "4 oz Ginger Beer"] },
  { name: "Mexican Mule", ingredients: ["2 oz Tequila", "1/2 oz Lime Juice", "4 oz Ginger Beer"] },
  { name: "Gin Gin Mule", ingredients: ["2 oz Gin", "3/4 oz Lime Juice", "1/2 oz Simple Syrup", "8 Mint Leaves", "2 oz Ginger Beer"] },
  { name: "Horses Neck", ingredients: ["2 oz Brandy", "4 oz Ginger Ale", "2 Dashes Angostura Bitters"] },
  { name: "Whiskey Highball", ingredients: ["2 oz Whisky", "4 oz Soda Water"] },
  { name: "Vodka Tonic", ingredients: ["2 oz Vodka", "4 oz Tonic Water"] },
  { name: "Vodka Lemon", ingredients: ["4 cl Vodka", "0,2 l Bitter Lemon"] },
  { name: "Kalimotxo", ingredients: ["0,2 l Rotwein", "0,2 l Cola"] },
  { name: "Weinschorle", ingredients: ["0,25 l Weißwein", "0,25 l Mineralwasser"] },
  { name: "Aperol Tonic", ingredients: ["2 oz Aperol", "4 oz Tonic Water"] },
  { name: "Pink Gin Tonic", ingredients: ["2 oz Pink Gin", "4 oz Tonic Water", "3 Raspberries"] },
  { name: "Gin Rickey", ingredients: ["2 oz Gin", "1/2 oz Lime Juice", "4 oz Soda Water"] },
  { name: "Vodka Sour", ingredients: ["2 oz Vodka", "1 oz Lemon Juice", "1/2 oz Simple Syrup"] },
  { name: "Cointreau Fizz", ingredients: ["2 oz Cointreau", "1 oz Lime Juice", "3 oz Soda Water", "8 Mint Leaves"] },
  { name: "Virgin Mule", ingredients: ["1/2 oz Lime Juice", "5 oz Ginger Beer", "6 Mint Leaves"] },
  { name: "Virgin Colada", ingredients: ["1 oz Coconut Cream", "4 oz Pineapple Juice", "1 oz Cream"] },
  { name: "Virgin Mojito", ingredients: ["1 oz Lime Juice", "2 tsp Sugar", "8 Mint Leaves", "4 oz Soda Water"] },
  { name: "Shirley Temple", ingredients: ["4 oz Ginger Ale", "2 oz Lemonade", "1/2 oz Grenadine"] },
  { name: "Ipanema", ingredients: ["1 Lime", "2 tsp Brown Sugar", "4 oz Ginger Ale"] },
  { name: "Kiba", ingredients: ["4 oz Cherry Juice", "2 oz Banana Nectar"] },
  { name: "Coconut Kiss", ingredients: ["1 oz Coconut Cream", "3 oz Pineapple Juice", "1 oz Cream", "1/2 oz Grenadine"] },
  { name: "Florida Cocktail", ingredients: ["3 oz Orange Juice", "1 oz Grapefruit Juice", "1 oz Lemon Juice", "1 tsp Sugar"] },
  { name: "Cinderella", ingredients: ["2 oz Orange Juice", "2 oz Pineapple Juice", "1 oz Lemon Juice", "1/2 oz Grenadine"] },
  { name: "San Francisco", ingredients: ["2 oz Orange Juice", "2 oz Pineapple Juice", "1 oz Lemon Juice", "1/2 oz Grenadine", "2 Dashes Angostura Bitters"] },
  { name: "Arnold Palmer", ingredients: ["4 oz Iced Tea", "4 oz Lemonade"] },
  { name: "Cranberry Spritz", ingredients: ["3 oz Cranberry Juice", "3 oz Soda Water", "1/2 oz Lime Juice"] }
];

// Deutsche Suchbegriffe auf die englischen Namen im Katalog abbilden, damit
// "Wodka Sauer" oder "Erdbeer Daiquiri" ebenfalls Treffer liefern.
const SEARCH_SYNONYMS = {
  wodka: "vodka",
  whiskey: "whisky",
  likoer: "liqueur",
  zitrone: "lemon",
  zitronen: "lemon",
  limette: "lime",
  limetten: "lime",
  erdbeer: "strawberry",
  erdbeere: "strawberry",
  erdbeeren: "strawberry",
  himbeer: "raspberry",
  himbeere: "raspberry",
  pfirsich: "peach",
  ananas: "pineapple",
  apfel: "apple",
  kirsch: "cherry",
  kirsche: "cherry",
  kokos: "coconut",
  minze: "mint",
  gurke: "cucumber",
  orange: "orange",
  orangen: "orange",
  sauer: "sour",
  kaffee: "coffee",
  sahne: "cream",
  ingwer: "ginger",
  honig: "honey",
  zucker: "sugar",
  wasser: "water",
  bier: "beer",
  wein: "wine",
  rotwein: "red wine",
  weisswein: "white wine",
  sekt: "champagne",
  champagner: "champagne",
  traube: "grape",
  gefroren: "frozen",
  alkoholfrei: "virgin",
  heiss: "hot"
};
