// Offline-Katalog bekannter Cocktails für die Vorschlagsliste im
// "Hinzufügen"-Dialog. Er ersetzt die frühere Live-Suche bei TheCocktailDB:
// keine Netzwerkanfrage, kein API-Schlüssel, keine Kosten - und die Suche
// antwortet sofort, auch im Flugmodus.
//
// Die Reihenfolge ist grob nach Bekanntheit sortiert; die ersten Einträge
// erscheinen als Vorschläge, solange noch nichts getippt wurde.
// Die Zutaten stehen im selben Format wie in shared/data.js (Menge + Zutat
// in einem Text), damit die Art-Erkennung und die Alkoholmenge sie lesen.
const cocktailCatalog = [
  { name: "Mojito", ingredients: ["6 cl Light Rum", "3 cl Lime Juice", "2 TL Sugar", "8 Mint Leaves", "9 cl Soda Water"] },
  { name: "Margarita", ingredients: ["6 cl Tequila", "3 cl Triple Sec", "3 cl Lime Juice"] },
  { name: "Aperol Spritz", ingredients: ["6 cl Aperol", "9 cl Prosecco", "3 cl Soda Water"] },
  { name: "Moscow Mule", ingredients: ["6 cl Vodka", "1,5 cl Lime Juice", "12 cl Ginger Beer"] },
  { name: "Daiquiri", ingredients: ["6 cl Light Rum", "3 cl Lime Juice", "2 cl Simple Syrup"] },
  { name: "Old Fashioned", ingredients: ["6 cl Bourbon", "1 TL Sugar", "3 Dashes Angostura Bitters"] },
  { name: "Whiskey Sour", ingredients: ["6 cl Bourbon", "3 cl Lemon Juice", "2 cl Simple Syrup", "1,5 cl Egg White"] },
  { name: "Caipirinha", ingredients: ["6 cl Cachaca", "1 Lime", "2 TL Sugar"] },
  { name: "Cosmopolitan", ingredients: ["4,5 cl Vodka Citron", "1,5 cl Triple Sec", "1,5 cl Lime Juice", "3 cl Cranberry Juice"] },
  { name: "Espresso Martini", ingredients: ["6 cl Vodka", "1,5 cl Kahlua", "3 cl Espresso", "1 cl Simple Syrup"] },
  { name: "Hugo", ingredients: ["3 cl Elderflower Syrup", "12 cl Prosecco", "3 cl Soda Water", "8 Mint Leaves", "2 Lime Wedges"] },
  { name: "Long Island Iced Tea", ingredients: ["1,5 cl Vodka", "1,5 cl Light Rum", "1,5 cl Gin", "1,5 cl Tequila", "1,5 cl Triple Sec", "2 cl Lemon Juice", "6 cl Cola"] },
  { name: "Sex on the Beach", ingredients: ["4,5 cl Vodka", "1,5 cl Peach Schnapps", "6 cl Orange Juice", "6 cl Cranberry Juice"] },
  { name: "Mai Tai", ingredients: ["4,5 cl Dark Rum", "1,5 cl Light Rum", "1,5 cl Orange Curacao", "1,5 cl Orgeat Syrup", "3 cl Lime Juice"] },
  { name: "Manhattan", ingredients: ["6 cl Rye Whiskey", "3 cl Sweet Vermouth", "2 Dashes Angostura Bitters"] },
  { name: "Gin Fizz", ingredients: ["6 cl Gin", "3 cl Lemon Juice", "2 cl Simple Syrup", "9 cl Soda Water"] },
  { name: "Tom Collins", ingredients: ["6 cl Gin", "3 cl Lemon Juice", "1,5 cl Simple Syrup", "9 cl Soda Water"] },
  { name: "Bloody Mary", ingredients: ["6 cl Vodka", "12 cl Tomato Juice", "1,5 cl Lemon Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco", "1 Pinch Celery Salt"] },
  { name: "Screwdriver", ingredients: ["6 cl Vodka", "12 cl Orange Juice"] },
  { name: "Gin Basil Smash", ingredients: ["6 cl Gin", "3 cl Lemon Juice", "2 cl Simple Syrup", "10 Basil Leaves"] },
  { name: "Paloma", ingredients: ["6 cl Tequila", "1,5 cl Lime Juice", "12 cl Grapefruit Soda", "1 Pinch Salt"] },
  { name: "Dark and Stormy", ingredients: ["6 cl Dark Rum", "12 cl Ginger Beer", "1,5 cl Lime Juice"] },
  { name: "Pisco Sour", ingredients: ["6 cl Pisco", "3 cl Lime Juice", "2 cl Simple Syrup", "1,5 cl Egg White", "2 Dashes Angostura Bitters"] },
  { name: "Amaretto Sour", ingredients: ["6 cl Amaretto", "3 cl Lemon Juice", "1,5 cl Simple Syrup", "1,5 cl Egg White"] },
  { name: "White Russian", ingredients: ["6 cl Vodka", "3 cl Kahlua", "3 cl Cream"] },
  { name: "Mint Julep", ingredients: ["7,5 cl Bourbon", "1,5 cl Simple Syrup", "10 Mint Leaves"] },
  { name: "Sidecar", ingredients: ["6 cl Cognac", "2 cl Triple Sec", "2 cl Lemon Juice"] },
  { name: "Aviation", ingredients: ["6 cl Gin", "1,5 cl Maraschino Liqueur", "1 cl Creme de Violette", "2 cl Lemon Juice"] },
  { name: "Sazerac", ingredients: ["6 cl Rye Whiskey", "1 Sugar Cube", "3 Dashes Peychaud Bitters", "1 Dash Absinthe"] },
  { name: "Boulevardier", ingredients: ["4,5 cl Bourbon", "3 cl Campari", "3 cl Sweet Vermouth"] },
  { name: "Americano", ingredients: ["4,5 cl Campari", "4,5 cl Sweet Vermouth", "6 cl Soda Water"] },
  { name: "Bramble", ingredients: ["6 cl Gin", "3 cl Lemon Juice", "1,5 cl Simple Syrup", "1,5 cl Creme de Mure"] },
  { name: "French 75", ingredients: ["3 cl Gin", "1,5 cl Lemon Juice", "1,5 cl Simple Syrup", "9 cl Champagne"] },
  { name: "Zombie", ingredients: ["4,5 cl Dark Rum", "4,5 cl Light Rum", "3 cl Overproof Rum", "1,5 cl Falernum", "3 cl Lime Juice", "3 cl Grapefruit Juice", "1 TL Grenadine"] },
  { name: "Hurricane", ingredients: ["6 cl Dark Rum", "6 cl Light Rum", "3 cl Passion Fruit Syrup", "3 cl Lime Juice", "3 cl Orange Juice"] },
  { name: "Painkiller", ingredients: ["6 cl Dark Rum", "12 cl Pineapple Juice", "3 cl Orange Juice", "3 cl Coconut Cream", "1 Pinch Nutmeg"] },
  { name: "Blue Hawaii", ingredients: ["3 cl Light Rum", "3 cl Vodka", "3 cl Blue Curacao", "9 cl Pineapple Juice", "3 cl Sweet and Sour Mix"] },
  { name: "Swimming Pool", ingredients: ["4,5 cl Vodka", "1,5 cl Light Rum", "3 cl Coconut Cream", "9 cl Pineapple Juice", "1,5 cl Blue Curacao"] },
  { name: "Sea Breeze", ingredients: ["4,5 cl Vodka", "9 cl Cranberry Juice", "4,5 cl Grapefruit Juice"] },
  { name: "Bay Breeze", ingredients: ["4,5 cl Vodka", "9 cl Cranberry Juice", "4,5 cl Pineapple Juice"] },
  { name: "Madras", ingredients: ["4,5 cl Vodka", "9 cl Cranberry Juice", "4,5 cl Orange Juice"] },
  { name: "Woo Woo", ingredients: ["4,5 cl Vodka", "3 cl Peach Schnapps", "9 cl Cranberry Juice"] },
  { name: "Kamikaze", ingredients: ["3 cl Vodka", "3 cl Triple Sec", "3 cl Lime Juice"] },
  { name: "Lemon Drop Martini", ingredients: ["6 cl Vodka Citron", "1,5 cl Triple Sec", "2 cl Lemon Juice", "1,5 cl Simple Syrup"] },
  { name: "Appletini", ingredients: ["6 cl Vodka", "3 cl Apple Liqueur", "1,5 cl Lemon Juice"] },
  { name: "Pornstar Martini", ingredients: ["6 cl Vanilla Vodka", "1,5 cl Passoa", "3 cl Passion Fruit Puree", "1,5 cl Lime Juice", "6 cl Prosecco"] },
  { name: "French Martini", ingredients: ["6 cl Vodka", "1,5 cl Chambord", "6 cl Pineapple Juice"] },
  { name: "Clover Club", ingredients: ["6 cl Gin", "1,5 cl Raspberry Syrup", "2 cl Lemon Juice", "1,5 cl Egg White"] },
  { name: "Last Word", ingredients: ["2 cl Gin", "2 cl Green Chartreuse", "2 cl Maraschino Liqueur", "2 cl Lime Juice"] },
  { name: "Corpse Reviver No. 2", ingredients: ["2 cl Gin", "2 cl Cointreau", "2 cl Lillet Blanc", "2 cl Lemon Juice", "1 Dash Absinthe"] },
  { name: "Vesper", ingredients: ["9 cl Gin", "3 cl Vodka", "1,5 cl Lillet Blanc"] },
  { name: "Gimlet", ingredients: ["6 cl Gin", "2 cl Lime Juice", "1,5 cl Simple Syrup"] },
  { name: "Southside", ingredients: ["6 cl Gin", "3 cl Lime Juice", "2 cl Simple Syrup", "8 Mint Leaves"] },
  { name: "Bees Knees", ingredients: ["6 cl Gin", "2 cl Lemon Juice", "2 cl Honey Syrup"] },
  { name: "Penicillin", ingredients: ["6 cl Blended Scotch", "2 cl Lemon Juice", "2 cl Honey Ginger Syrup", "1 cl Islay Scotch"] },
  { name: "Godfather", ingredients: ["6 cl Scotch", "3 cl Amaretto"] },
  { name: "Godmother", ingredients: ["6 cl Vodka", "3 cl Amaretto"] },
  { name: "Rusty Nail", ingredients: ["6 cl Scotch", "3 cl Drambuie"] },
  { name: "Rob Roy", ingredients: ["6 cl Scotch", "3 cl Sweet Vermouth", "2 Dashes Angostura Bitters"] },
  { name: "Vieux Carre", ingredients: ["3 cl Rye Whiskey", "3 cl Cognac", "3 cl Sweet Vermouth", "1 TL Benedictine", "2 Dashes Peychaud Bitters"] },
  { name: "Brooklyn", ingredients: ["6 cl Rye Whiskey", "3 cl Dry Vermouth", "1 cl Maraschino Liqueur", "1 cl Amaro"] },
  { name: "Martinez", ingredients: ["4,5 cl Gin", "4,5 cl Sweet Vermouth", "1 TL Maraschino Liqueur", "2 Dashes Orange Bitters"] },
  { name: "Hanky Panky", ingredients: ["4,5 cl Gin", "4,5 cl Sweet Vermouth", "2 Dashes Fernet Branca"] },
  { name: "Negroni Sbagliato", ingredients: ["3 cl Campari", "3 cl Sweet Vermouth", "6 cl Prosecco"] },
  { name: "Garibaldi", ingredients: ["4,5 cl Campari", "12 cl Orange Juice"] },
  { name: "Bicicletta", ingredients: ["4,5 cl Campari", "9 cl White Wine", "3 cl Soda Water"] },
  { name: "Campari Spritz", ingredients: ["6 cl Campari", "9 cl Prosecco", "3 cl Soda Water"] },
  { name: "Limoncello Spritz", ingredients: ["6 cl Limoncello", "9 cl Prosecco", "3 cl Soda Water"] },
  { name: "Lillet Wild Berry", ingredients: ["6 cl Lillet Blanc", "12 cl Wild Berry Lemonade"] },
  { name: "Lillet Vive", ingredients: ["6 cl Lillet Blanc", "12 cl Tonic Water", "2 Strawberries", "6 Mint Leaves"] },
  { name: "Aperol Sour", ingredients: ["6 cl Aperol", "3 cl Lemon Juice", "1,5 cl Simple Syrup", "1,5 cl Egg White"] },
  { name: "Mimosa", ingredients: ["9 cl Champagne", "9 cl Orange Juice"] },
  { name: "Bucks Fizz", ingredients: ["12 cl Champagne", "6 cl Orange Juice"] },
  { name: "Champagne Cocktail", ingredients: ["12 cl Champagne", "1 Sugar Cube", "2 Dashes Angostura Bitters", "1 cl Cognac"] },
  { name: "Death in the Afternoon", ingredients: ["3 cl Absinthe", "12 cl Champagne"] },
  { name: "Kir", ingredients: ["12 cl White Wine", "1,5 cl Creme de Cassis"] },
  { name: "Rossini", ingredients: ["12 cl Prosecco", "6 cl Strawberry Puree"] },
  { name: "Sgroppino", ingredients: ["6 cl Prosecco", "3 cl Vodka", "2 Scoops Lemon Sorbet"] },
  { name: "Caipiroska", ingredients: ["6 cl Vodka", "1 Lime", "2 TL Sugar"] },
  { name: "Caipirissima", ingredients: ["6 cl Light Rum", "1 Lime", "2 TL Sugar"] },
  { name: "Batida de Coco", ingredients: ["6 cl Cachaca", "6 cl Coconut Milk", "3 cl Condensed Milk"] },
  { name: "Ti Punch", ingredients: ["6 cl Rhum Agricole", "1 TL Cane Syrup", "1 Lime Wedge"] },
  { name: "Strawberry Daiquiri", ingredients: ["6 cl Light Rum", "3 cl Lime Juice", "1,5 cl Simple Syrup", "5 Strawberries"] },
  { name: "Frozen Margarita", ingredients: ["6 cl Tequila", "3 cl Triple Sec", "3 cl Lime Juice", "1 Cup Crushed Ice"] },
  { name: "Tommys Margarita", ingredients: ["6 cl Tequila", "3 cl Lime Juice", "1,5 cl Agave Syrup"] },
  { name: "Michelada", ingredients: ["0,33 l Lager Beer", "3 cl Lime Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco", "1 Pinch Salt"] },
  { name: "Bloody Caesar", ingredients: ["6 cl Vodka", "12 cl Clamato Juice", "2 Dashes Worcestershire Sauce", "2 Dashes Tabasco"] },
  { name: "El Diablo", ingredients: ["6 cl Tequila", "1,5 cl Creme de Cassis", "1,5 cl Lime Juice", "9 cl Ginger Beer"] },
  { name: "Batanga", ingredients: ["6 cl Tequila", "1,5 cl Lime Juice", "12 cl Cola", "1 Pinch Salt"] },
  { name: "Mezcal Negroni", ingredients: ["3 cl Mezcal", "3 cl Campari", "3 cl Sweet Vermouth"] },
  { name: "Oaxaca Old Fashioned", ingredients: ["4,5 cl Tequila", "1,5 cl Mezcal", "1 TL Agave Syrup", "2 Dashes Angostura Bitters"] },
  { name: "Naked and Famous", ingredients: ["2 cl Mezcal", "2 cl Yellow Chartreuse", "2 cl Aperol", "2 cl Lime Juice"] },
  { name: "Jungle Bird", ingredients: ["4,5 cl Dark Rum", "2 cl Campari", "4,5 cl Pineapple Juice", "1,5 cl Lime Juice", "1,5 cl Simple Syrup"] },
  { name: "Chi Chi", ingredients: ["6 cl Vodka", "3 cl Coconut Cream", "9 cl Pineapple Juice"] },
  { name: "Rum Runner", ingredients: ["3 cl Dark Rum", "3 cl Light Rum", "1,5 cl Banana Liqueur", "1,5 cl Blackberry Liqueur", "3 cl Lime Juice", "1,5 cl Grenadine"] },
  { name: "Bahama Mama", ingredients: ["3 cl Dark Rum", "3 cl Coconut Rum", "6 cl Pineapple Juice", "3 cl Orange Juice", "1,5 cl Grenadine"] },
  { name: "Miami Vice", ingredients: ["3 cl Light Rum", "3 cl Coconut Cream", "6 cl Pineapple Juice", "6 cl Strawberry Puree"] },
  { name: "Mudslide", ingredients: ["3 cl Vodka", "3 cl Kahlua", "3 cl Baileys", "3 cl Cream"] },
  { name: "Grasshopper", ingredients: ["3 cl Creme de Menthe", "3 cl Creme de Cacao", "3 cl Cream"] },
  { name: "Brandy Alexander", ingredients: ["4,5 cl Cognac", "3 cl Creme de Cacao", "3 cl Cream"] },
  { name: "Golden Cadillac", ingredients: ["3 cl Galliano", "3 cl Creme de Cacao", "3 cl Cream"] },
  { name: "Toasted Almond", ingredients: ["3 cl Amaretto", "3 cl Kahlua", "6 cl Cream"] },
  { name: "B-52", ingredients: ["1,5 cl Kahlua", "1,5 cl Baileys", "1,5 cl Grand Marnier"] },
  { name: "Baby Guinness", ingredients: ["2 cl Kahlua", "1 cl Baileys"] },
  { name: "Slippery Nipple", ingredients: ["2 cl Sambuca", "2 cl Baileys", "1 Dash Grenadine"] },
  { name: "Mexicaner", ingredients: ["4 cl Vodka", "2 cl Tomatensaft", "1 cl Chilisauce", "1 Spritzer Zitronensaft"] },
  { name: "Jägerbomb", ingredients: ["3 cl Jägermeister", "0,25 l Energydrink"] },
  { name: "Irish Coffee", ingredients: ["4,5 cl Irish Whiskey", "12 cl Coffee", "1 TL Brown Sugar", "3 cl Whipped Cream"] },
  { name: "Espresso Tonic", ingredients: ["3 cl Espresso", "15 cl Tonic Water"] },
  { name: "Lumumba", ingredients: ["4,5 cl Brandy", "15 cl Hot Chocolate", "3 cl Whipped Cream"] },
  { name: "Snowball", ingredients: ["6 cl Advocaat", "1,5 cl Lime Juice", "12 cl Lemonade"] },
  { name: "Egg Nog", ingredients: ["4,5 cl Brandy", "1,5 cl Dark Rum", "1 Egg", "1 TL Sugar", "12 cl Milk", "1 Pinch Nutmeg"] },
  { name: "Hot Toddy", ingredients: ["6 cl Whisky", "1 TL Honey", "1,5 cl Lemon Juice", "12 cl Hot Water"] },
  { name: "Glühwein", ingredients: ["0,2 l Rotwein", "1 TL Zucker", "1 Zimtstange", "2 Nelken", "1 Orangenscheibe"] },
  { name: "Feuerzangenbowle", ingredients: ["0,2 l Rotwein", "3 cl Overproof Rum", "1 Zuckerhut", "1 Zimtstange", "1 Orangenscheibe"] },
  { name: "Pimms Cup", ingredients: ["6 cl Pimms No. 1", "12 cl Lemonade", "1 Cucumber Slice", "6 Mint Leaves"] },
  { name: "Salty Dog", ingredients: ["6 cl Vodka", "12 cl Grapefruit Juice", "1 Pinch Salt"] },
  { name: "Greyhound", ingredients: ["6 cl Vodka", "12 cl Grapefruit Juice"] },
  { name: "Harvey Wallbanger", ingredients: ["4,5 cl Vodka", "12 cl Orange Juice", "1,5 cl Galliano"] },
  { name: "Fuzzy Navel", ingredients: ["6 cl Peach Schnapps", "12 cl Orange Juice"] },
  { name: "Melon Ball", ingredients: ["3 cl Vodka", "3 cl Midori", "9 cl Pineapple Juice"] },
  { name: "Midori Sour", ingredients: ["6 cl Midori", "3 cl Lemon Juice", "1,5 cl Simple Syrup", "6 cl Soda Water"] },
  { name: "Japanese Slipper", ingredients: ["3 cl Midori", "3 cl Cointreau", "3 cl Lemon Juice"] },
  { name: "Illusion", ingredients: ["3 cl Vodka", "3 cl Midori", "1,5 cl Triple Sec", "6 cl Pineapple Juice"] },
  { name: "Scorpion", ingredients: ["6 cl Light Rum", "3 cl Brandy", "6 cl Orange Juice", "3 cl Lemon Juice", "1,5 cl Orgeat Syrup"] },
  { name: "Fog Cutter", ingredients: ["4,5 cl Light Rum", "1,5 cl Gin", "1,5 cl Brandy", "3 cl Orange Juice", "1,5 cl Lemon Juice", "1,5 cl Orgeat Syrup"] },
  { name: "Three Dots and a Dash", ingredients: ["4,5 cl Rhum Agricole", "1,5 cl Dark Rum", "1,5 cl Honey Syrup", "1,5 cl Falernum", "1,5 cl Lime Juice", "1,5 cl Orange Juice"] },
  { name: "Singapore Sling", ingredients: ["4,5 cl Gin", "1,5 cl Cherry Brandy", "1 cl Cointreau", "1 cl Benedictine", "1,5 cl Lime Juice", "6 cl Pineapple Juice", "1 cl Grenadine"] },
  { name: "Hemingway Daiquiri", ingredients: ["6 cl Light Rum", "2 cl Lime Juice", "1,5 cl Grapefruit Juice", "1 cl Maraschino Liqueur"] },
  { name: "Between the Sheets", ingredients: ["3 cl Cognac", "3 cl Light Rum", "3 cl Triple Sec", "1,5 cl Lemon Juice"] },
  { name: "Mary Pickford", ingredients: ["6 cl Light Rum", "4,5 cl Pineapple Juice", "1 TL Maraschino Liqueur", "1 TL Grenadine"] },
  { name: "El Presidente", ingredients: ["6 cl Light Rum", "2 cl Dry Vermouth", "1,5 cl Orange Curacao", "1 TL Grenadine"] },
  { name: "Bacardi Cocktail", ingredients: ["6 cl Bacardi Light Rum", "2 cl Lime Juice", "1,5 cl Grenadine"] },
  { name: "New York Sour", ingredients: ["6 cl Bourbon", "3 cl Lemon Juice", "2 cl Simple Syrup", "1,5 cl Red Wine"] },
  { name: "Paper Plane", ingredients: ["2 cl Bourbon", "2 cl Aperol", "2 cl Amaro Nonino", "2 cl Lemon Juice"] },
  { name: "Gold Rush", ingredients: ["6 cl Bourbon", "2 cl Lemon Juice", "2 cl Honey Syrup"] },
  { name: "Whiskey Smash", ingredients: ["6 cl Bourbon", "2 cl Lemon Juice", "1,5 cl Simple Syrup", "8 Mint Leaves"] },
  { name: "Blood and Sand", ingredients: ["2 cl Scotch", "2 cl Cherry Heering", "2 cl Sweet Vermouth", "2 cl Orange Juice"] },
  { name: "Suffering Bastard", ingredients: ["3 cl Gin", "3 cl Brandy", "1,5 cl Lime Juice", "12 cl Ginger Beer", "2 Dashes Angostura Bitters"] },
  { name: "Kentucky Mule", ingredients: ["6 cl Bourbon", "1,5 cl Lime Juice", "12 cl Ginger Beer"] },
  { name: "Mexican Mule", ingredients: ["6 cl Tequila", "1,5 cl Lime Juice", "12 cl Ginger Beer"] },
  { name: "Gin Gin Mule", ingredients: ["6 cl Gin", "2 cl Lime Juice", "1,5 cl Simple Syrup", "8 Mint Leaves", "6 cl Ginger Beer"] },
  { name: "Horses Neck", ingredients: ["6 cl Brandy", "12 cl Ginger Ale", "2 Dashes Angostura Bitters"] },
  { name: "Whiskey Highball", ingredients: ["6 cl Whisky", "12 cl Soda Water"] },
  { name: "Vodka Tonic", ingredients: ["6 cl Vodka", "12 cl Tonic Water"] },
  { name: "Vodka Lemon", ingredients: ["4 cl Vodka", "0,2 l Bitter Lemon"] },
  { name: "Kalimotxo", ingredients: ["0,2 l Rotwein", "0,2 l Cola"] },
  { name: "Weinschorle", ingredients: ["0,25 l Weißwein", "0,25 l Mineralwasser"] },
  { name: "Aperol Tonic", ingredients: ["6 cl Aperol", "12 cl Tonic Water"] },
  { name: "Pink Gin Tonic", ingredients: ["6 cl Pink Gin", "12 cl Tonic Water", "3 Raspberries"] },
  { name: "Gin Rickey", ingredients: ["6 cl Gin", "1,5 cl Lime Juice", "12 cl Soda Water"] },
  { name: "Vodka Sour", ingredients: ["6 cl Vodka", "3 cl Lemon Juice", "1,5 cl Simple Syrup"] },
  { name: "Cointreau Fizz", ingredients: ["6 cl Cointreau", "3 cl Lime Juice", "9 cl Soda Water", "8 Mint Leaves"] },
  { name: "Virgin Mule", ingredients: ["1,5 cl Lime Juice", "15 cl Ginger Beer", "6 Mint Leaves"] },
  { name: "Virgin Colada", ingredients: ["3 cl Coconut Cream", "12 cl Pineapple Juice", "3 cl Cream"] },
  { name: "Virgin Mojito", ingredients: ["3 cl Lime Juice", "2 TL Sugar", "8 Mint Leaves", "12 cl Soda Water"] },
  { name: "Shirley Temple", ingredients: ["12 cl Ginger Ale", "6 cl Lemonade", "1,5 cl Grenadine"] },
  { name: "Ipanema", ingredients: ["1 Lime", "2 TL Brown Sugar", "12 cl Ginger Ale"] },
  { name: "Kiba", ingredients: ["12 cl Cherry Juice", "6 cl Banana Nectar"] },
  { name: "Coconut Kiss", ingredients: ["3 cl Coconut Cream", "9 cl Pineapple Juice", "3 cl Cream", "1,5 cl Grenadine"] },
  { name: "Florida Cocktail", ingredients: ["9 cl Orange Juice", "3 cl Grapefruit Juice", "3 cl Lemon Juice", "1 TL Sugar"] },
  { name: "Cinderella", ingredients: ["6 cl Orange Juice", "6 cl Pineapple Juice", "3 cl Lemon Juice", "1,5 cl Grenadine"] },
  { name: "San Francisco", ingredients: ["6 cl Orange Juice", "6 cl Pineapple Juice", "3 cl Lemon Juice", "1,5 cl Grenadine", "2 Dashes Angostura Bitters"] },
  { name: "Arnold Palmer", ingredients: ["12 cl Iced Tea", "12 cl Lemonade"] },
  { name: "Cranberry Spritz", ingredients: ["9 cl Cranberry Juice", "9 cl Soda Water", "1,5 cl Lime Juice"] }
];

// Deutsche Suchbegriffe auf die englischen Namen im Katalog abbilden, damit
// "Wodka Sauer" oder "Erdbeer Daiquiri" ebenfalls Treffer liefern.
const SEARCH_SYNONYMS = {
  wodka: "vodka",
  whiskey: "whisky",
  likoer: "liqueur",
  zitrone: "lemon",
  zitronen: "lemon",
  limette: "lime",
  limetten: "lime",
  erdbeer: "strawberry",
  erdbeere: "strawberry",
  erdbeeren: "strawberry",
  himbeer: "raspberry",
  himbeere: "raspberry",
  pfirsich: "peach",
  ananas: "pineapple",
  apfel: "apple",
  kirsch: "cherry",
  kirsche: "cherry",
  kokos: "coconut",
  minze: "mint",
  gurke: "cucumber",
  orange: "orange",
  orangen: "orange",
  sauer: "sour",
  kaffee: "coffee",
  sahne: "cream",
  ingwer: "ginger",
  honig: "honey",
  zucker: "sugar",
  wasser: "water",
  bier: "beer",
  wein: "wine",
  rotwein: "red wine",
  weisswein: "white wine",
  sekt: "champagne",
  champagner: "champagne",
  traube: "grape",
  gefroren: "frozen",
  alkoholfrei: "virgin",
  heiss: "hot"
};
